### ISSUE TITLE
Support for BUFR to IODA Converter for Scatterometer Winds 

### ISSUE THREAD

**Issue by ilianagenkova** [JCSDA-internal/ioda-converters#443] opened 2021-02-25 04:49 UTC
Provide support with scatterometer winds - files names, mnemonics, used BUFR tables, etc.

Scatterometer winds (currently only ASCAT are assimilated) could be found in two operational files:
*ascatw* (i.e. gdas.t12z.ascatw.tm00.bufr_d) and *prepbufr* (i.e. gdas.t12z.prepbufr). The *ascatw* files contain the quality controlled *ascatt* files. These same winds are also put into *prepbufr* file for GSI use.
*ascatw* and *prepbufr* files use different BUFR tables.

 *ascatw* bufr table has the following mnemonics:
 MNEMONIC  - SEQUENCE 
 NC012122  - YEAR  MNTH  DAYS  HOUR  MINU  SECO  CLAT  CLON  CTCN  WD10  WS10  
 NC012122 - WVCQ  RPID  SAID  ACAV  BSCD  LKCS   

*prepbufr* uses [prep-BUFR ](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/obsproc_prep.v5.3.0/fix/prepobs_prep.bufrtable
)

Validated the BUFR to IODA Converter for Scatterometer winds (#412 )

**Comment by ilianagenkova** [comment] 2021-03-26 22:39
The work on this issue was extended to match progress in #412 
First the scatterometer winds  converter was designed to be applied to *ascatw* operational bufr files. Now it could also be applied to *prepbufr* operational files (they contain the same obs as in *ascatw*, but with added quality flags).

The conversion was validated to work fine.

**Comment by gthompsnJCSDA** [comment] 2021-07-08 20:51
It is not clear that this issue is not a near duplicate of a similar issue.  I will go ahead and close this one.  If that is incorrect, please edit either this one or the other to make clear what is different in this one and the other one to describe the work that needs to be done.  And you can always re-open a closed issue.

**Closed by gthompsnJCSDA** 2021-07-08 20:51 UTC
Labels: OBS1

**Comment by ilianagenkova** [comment] 2021-07-09 01:37
It is ok that you closed it, @gthompsnJCSDA . The work was done already. Thanks!
