### ISSUE TITLE
ioda converter issue for gnssro obs testing file

### ISSUE THREAD

**Issue by gmao-yzhu** [JCSDA-internal/ioda-converters#1072] opened 2022-09-28 13:53 UTC
A problem was encountered when running a test on gnssro observation operator for the GMAO GEOS system. 
We saw error message that nrecs != icount, and then the test aborted, but the ctest printed out “0 tests failed out of 2”.

nrecs and icount are calculated in ufo/src/ufo/operators/gnssro/BndNBAM/ufo_gnssro_bndnbam_mod.F90, I copy and paste related codes below:

nrecs   = obsspace_get_nrecs(obss)

call obsspace_get_recnum(obss, obsRecnum)
icount = 1
do iobs = 1, nlocs-1
    if (obsRecnum(iobs+1) /= obsRecnum(iobs)) then
         icount = icount +1  !counting number of records
    end if
end do 

We took a close look. It seems our testing obsdatain obsfile may have a problem with record number.

I printed out obsRecnum(iobs), obsRecnum(iobs+1), and icount in the loop “do iobs = 1, nlocs-1”. I’m wondering if the pattern of obsRecnum doesn’t look right. I copy and paste a small part of the printout here:

 ufo_gnssro_bndnbam_simobs:iobs=        1256  obsRecnum(iobs)= 5  obsRecnum(iobs+1)=  5

 ufo_gnssro_bndnbam_simobs:icount=           6

 ufo_gnssro_bndnbam_simobs:iobs=        1257  obsRecnum(iobs)= 5  obsRecnum(iobs+1)=  5

 ufo_gnssro_bndnbam_simobs:icount=           6

 ufo_gnssro_bndnbam_simobs:iobs=        1258  obsRecnum(iobs)= 5  obsRecnum(iobs+1)=  2

 ufo_gnssro_bndnbam_simobs:icount=           6

 ufo_gnssro_bndnbam_simobs:iobs=        1259  obsRecnum(iobs)= 2  obsRecnum(iobs+1)=  2

 ufo_gnssro_bndnbam_simobs:icount=           7

 ufo_gnssro_bndnbam_simobs:iobs=        1260  obsRecnum(iobs)= 2  obsRecnum(iobs+1)=  2

After obsRecnum(iobs+1)=  5, obsRecnum(iobs+1) becomes 2 again.

Here is the IODA-converter PR jianjun submitted and used to generate the obs testing file, which was already merged to the develop branch.
[https://github.com/JCSDA-internal/ioda-converters/pull/1038/files](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJCSDA-internal%2Fioda-converters%2Fpull%2F1038%2Ffiles&data=05%7C01%7Cyanqiu.zhu%40nasa.gov%7C9b4c318aa90c4a261ee908daa1014334%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637999324058240309%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Sa9znKILKxxyuARYe3UZQFdHU%2FACbnEDaGr6wkzfW7g%3D&reserved=0)

It seems there are still issues somewhere in the converter. Hailing is taking a close look and try to resolve the issue.

**Comment by BenjaminRuston** [comment] 2022-09-28 15:56
@gmao-yzhu are you planning to use this converter for your first implementation of JEDI, there are converters for the 6-hourly files of GNSS-RO data in NCEP BUFR

**Comment by hailingz** [comment] 2022-09-28 16:03
I have looked at the error message and found that error was caused by the "broken"  observations in the same profile. For example, the record_number of a "normal" IODA file would be "1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,.......". The record_number of Yanqiu's data is like "1,1,1,1,2,2,2,2,1,1,2,2,2,2,2,2,1,1,1,1,3,3,3,3,3,3,3,3,......."

(assuming 10 observations per profile)

By calling "call obsspace_get_recnum(obss, obsRecnum)" and using the check of "if (obsRecnum(iobs+1) /= obsRecnum(iobs)) then", each consecutive segment (based on the record_number) is treated as a new profile. Therefore, there are more icount than actual nrecs.

An ioda converter was designed to ensure the consecutive sorting for all profiles. Use of this converter will avoid the error.
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/gnssro/gnssro_gsidiag2ioda.f90

The one Yanqiu used: https://github.com/JCSDA-internal/ioda-converters/pull/1038/files

In addition, we use the gdas_jedi GSI branch to generate GSI diag files if you want to compare with yours.
https://github.com/JCSDA-internal/GSI/blob/feature/jedi_gdas/

**Comment by srherbener** [comment] 2022-09-28 16:21
Here's some clarification and recommendation about this issue.

An ObsSpace object creates a C++ std::map data structure (named recidx_) that holds which locations from the input file belong to which records that were created from the `obsgrouping:` specs in the YAML. The std::map also keeps track of the sort order of the locations within a given record. Note that if the locations that belong to a single record are presented in the file in a non-contiguous fashion (Yanqui's data example above), the recidx_ data structure will get built properly.

Unfortunately, Fortran does not have a std::map equivalent and it would take a significant amount of work to provide an interface in Fortran to the ObsSpace recidx_ structure.

The gnssro obs operator is written in Fortran, and to workaround the Fortran interface issue, @hailing's conversion method includes a step to pre-sort the incoming data so that all locations for a given record number are presented to ioda in a contiguous fashion. Given that step, the check that is throwing the error in the gnssro obs operator will work properly.

At this point it seems to me that doing the pre-sort of the incoming data in all of the gnssro converters is the best way to get something working as quickly as possible. However, for the long term it would be best to solve the Fortran interface issue so that the converter pre-sort step could be avoided.

Does this sound like a good approach to resolving this issue?

Thanks!

**Comment by hailingz** [comment] 2022-09-28 17:21
Thank you so much @srherbener for your explanation. I was about to assign you.

**Comment by gmao-yzhu** [comment] 2022-09-28 20:16
@srherbener @hailingz @BenjaminRuston Thanks very much for your help and explanation. Doing the pre-sort of the incoming data in the gnssro converters sounds good to us. When we had a meeting with Hailing this morning, she showed us what she has done with sorting. That is very helpful. Jianjun is working on this now. 

@BenjaminRuston Hailing showed us three converters (one is a converter from WMO bufr to ioda format you wrote). We are using the converter that converts a gsidiag to ioda format for our testing to ensure the data are used consistently between GEOS and UFO. We are also planning to use this converter for our first implementation of JEDI.

**Comment by gmao-jjin3** [comment] 2022-09-29 02:19
@danholdaway @gmao-yzhu Here is a what I am going to do at the end of the function "def grabobsidx(obsdata, platform, var)" in gsi_ncdiag.py.  Basically, it groups 'record_number' as @hailingz 's Fortran code.

```
    if var == 'bend':
##      Re-arrange "idx" in regards to "record_number"
        all_record_number = obsdata['record_number'][:]
        record_number = [all_record_number[i] for i in idx]
        id_rdnum_sort = sorted(range(len(record_number)),key=record_number.__getitem__)
        idx_new = [idx[i] for i in id_rdnum_sort]

##      replace "idx"  by idx_new
        idx = idx_new

```

**Comment by hailingz** [comment] 2022-11-08 17:14
Closing this because cause was found. We provided the converters used in obs team.

**Comment by gmao-jjin3** [comment] 2022-11-19 04:17
This issue now can be solved by the updated "gsi_ncdiag.py" in IODAconv: https://github.com/JCSDA-internal/ioda-converters/pull/1089 .

**Closed** 2022-11-19 04:25 UTC
